server:
    port: 8081

spring:
    application:
        name: library

    datasource:
        url: jdbc:mysql://localhost:3306/casa
        username: user
        password: book

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop

        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect