version: "3.5"
services:
  mysql:
    container_name: mysql_container
    image: mysql
    environment:
      MYSQL_DATABASE: 'casa'
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-book}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - '3306:3306'
    restart: unless-stopped